### ISSUE TITLE
Safari | Audio HLS: poster image is not displayed

### ISSUE THREAD

**Issue by fdambrosio** [jwplayer/jwplayer#1330] opened 2016-07-21 13:42 UTC
### Expected Behavior

When the player with HLS audio is ready or it's playing or it's paused, I expect that the poster image is displayed on Safari. 
### Actual Behavior

With Safari (audio player is loaded in html5 mode) the poster image isn't displayed in any case: ready, pause, playing. When player is loaded the poster is showed only 1 second. 
I think that there's some problems with skin too because I see gray bars at the top and bottom of the player, even above the control bar.
### Steps to reproduce
1. setup jwplayer HLS audio + image with Jwp 7.5.0 RC.1
2. open page with Safari
3. poster is not showed 
4. demo: http://www.fdambrosio.net/test/player7/safari.html
### Environment
- iMac
- MacOS 10.11.5 
- Safari 9.1.1
- Jwp 7.5.0 RC.1

demo: http://www.fdambrosio.net/test/player7/safari.html

**Comment by johnBartos** [comment] 2016-07-22 14:53
This is a known issue - on Chrome & FF, we make the video tag transparent to show the poster image behind it. Safari can't/won't make it transparent & renders as a black box instead.

**Comment by robwalch** [comment] 2016-07-22 16:12
...and the reason the video is on top of the poster is to display webvtt captions if present.

**Comment by fdambrosio** [comment] 2016-07-23 15:26
Ok, thanks for the answer, so we'll never have poster on Safari?

**Comment by robwalch** [comment] 2016-07-23 20:26
File a radar with Apple to allow transparency on video elements playing audio only sources. We'll do the same.

**Comment by robwalch** [comment] 2016-07-23 20:28
If you know you are playing audio and don't need captions you can display the video tag as hidden with CSS to show the poster. Is this something you need the player to do, or do need captions as well?

**Comment by fdambrosio** [comment] 2016-07-25 09:49
Yes, we need audio & poster image & captions that we show automatically by default

**Comment by smfr** [comment] 2016-09-30 01:02
I'm confused by this report. I see a poster image in Safari 10:
![jwplayer](https://cloud.githubusercontent.com/assets/20968/18977387/baf5091e-866e-11e6-859b-9d6ae304628b.png)

Is this not what it's supposed to look like?

You should also clarify that you're talking about the JWP poster, not <video poster="">.

**Comment by smfr** [comment] 2016-09-30 01:02
My tags were eaten. Not `<video poster="foo.png">`

**Comment by robwalch** [comment] 2016-09-30 21:32
The bug is no longer reproducible in this test case because the media is not accessible and has been hidden by the player. When an audio only stream is loaded in a video tag in Safari 10, the video tag is not transparent.

**Comment by smfr** [comment] 2016-09-30 21:33
Can I get a working test case?

**Comment by robwalch** [comment] 2016-10-01 20:51
https://content.jwplatform.com/previews/7pGhTmER-WbTtnKtI

All you need to set this up is an audio file and a poster image

```js
jwplayer('player').setup({
    file: '//content.jwplatform.com/videos/7pGhTmER-JwK18pVy.m4a',
    image: '//content.jwplatform.com/thumbs/7pGhTmER-720.jpg'
});
```

**Comment by smfr** [comment] 2016-10-02 01:19
In Safari the `<div class="jw-preview jw-reset"></div>` div has no background-image style set on it. I never hit the JS that does `"style='background-image: url(...)`, even with a different user agent. So this is either a bug in JWPlayer, or a JavaScript bug, but that would be easier to debug with non-minified JS.

**Comment by johanberonius** [comment] 2016-10-13 14:14
I experienced this problem too and solved it locally in my environment by setting the poster-attribute on the video-element using code similar to this example.
The poster image will automatically be visible until the first video frame is displayed, or for audio-only it will allways be visible. (exept in fullscreen on iPhone)
```
jwplayer().on('ready', function() {
    // Set poster image for video element to avoid black background for audio-only programs.
    document.getElementById(this.id).getElementsByTagName('video')[0].setAttribute('poster', this.getConfig().image);
});
```

**Comment by fdambrosio** [comment] 2016-10-19 19:44
Thank you @johanberonius ! Your workaround works with captions too!

**Comment by johanberonius** [comment] 2016-10-24 08:54
A test page where the poster image is set on the video element when the player is ready is available here:
http://rawgit.com/sveriges-utbildningsradio/jwplayer-test/master/video-poster-image.html

My guess to why the video element is not transparent in Safari is that a audio-only stream via HLS is actually served as a blank video stream with a MP3-soundtrack. `CODECS="mp4a.40.34"`

**Comment by fdambrosio** [comment] 2016-11-28 16:50
Hi, this issue will be fixed in the next release?

**Comment by fdambrosio** [comment] 2017-01-18 15:18
This issue is still present with 7.9.0 beta.2

**Comment by johnBartos** [comment] 2017-05-15 16:03
@fdambrosio Posting the workaround would be great; we're hesitant to fix this bug due to CORS issues and issues with Safari's video tag.

**Comment by lakshmipq** [comment] 2018-06-28 12:07
Sorry to review this old thread ... but does anyone have a work around for this for 7.9.12 ? Player is not displayed in IE and Safari. I noticed onReady() is not  being called at all in IE and safari which may be the root cause of these issues.

**Comment by robwalch** [comment] 2018-06-29 13:01
@lakshmipq the latest versions of the player are 8.4.1 and 7.12.12 for LTS.

We’re not aware of any issues with the “ready” event. Have you tried upgrading or using the ‘on(“ready”, callback)’ syntax?

**Comment by lakshmipq** [comment] 2018-06-29 13:48
Sorry! my bad ! I meant I am using 7.12.13 ( but cant go higher due to some internal reasons)	
I have used but it never seems to get invoked in IE ( but does on chrome ) :
jwplayer("previewAudio").onReady(function(){ console.log(" Print me ") });

The issues I face in IE-11 & Safari when using playlist is : ( everything works fine in chrome/FF on Mac and Windows )
1. JWplayer does not appear, onReady() does not call
2. I do inspect and remove the classes "jwplayer jw-reset jw-state-setup jw-skin-seven jw-stretch-uniform jw-flag-audio-player jw-ie jw-flag-media-audio" . 
3. Then, when I put my cursor on the <div> where the player is supposed to appear - I can see the cursor transform to a hand and I can now click randomly and the player plays the audio i.e invisible

**Comment by robwalch** [comment] 2018-06-29 17:01
@lakshmipq is you are not getting a "ready" event, perhaps setup is failing. `setup` should always result in either one "ready" event or one "setupError" event firing. Are you getting a setup error? That would explain the player not appearing. It could be you are not providing any media that is compatible with the browsers that are failing.

**Comment by robwalch** [comment] 2018-06-29 17:03
closing this issue as the poster bug has been fixed in v8. @lakshmipq  we can continue the conversation here, but opening a new issue would be best that includes your setup and browser details.

**Closed by robwalch** 2018-06-29 17:03 UTC
Labels: bug, third-party
