### ISSUE TITLE
Captions under controlbar with HLS audio stream

### ISSUE THREAD

**Issue by fdambrosio** [jwplayer/jwplayer#1067] opened 2016-02-23 13:43 UTC
Hi, 
there's a problem with 7.3.0 with captions and audio HLS stream: the vtt captions slide under the control bar when the mouse cursor go outside the player screen.

**Comment by robwalch** [comment] 2016-02-23 18:58
Thanks @fdambrosio,

We're adding this scenario to our test cases and discussing solutions.

Can you provide a little more info on which devices and browsers you're seeing this issue on?

**Comment by kylesessions** [comment] 2016-02-24 21:29
I'm experiencing a similar issue that I believe might be related. I'm using version 7.3.2. The problem I'm seeing is that, when the video controls are not displayed, the captions are displayed too low in the video frame, and the bottom of them gets cut off:

![img_0013](https://cloud.githubusercontent.com/assets/11525617/13301520/2b4e2414-dafa-11e5-859b-86ebd0562300.PNG)

When video controls are displayed, the entire caption does display, but it displays behind the video controls:

![img_0012](https://cloud.githubusercontent.com/assets/11525617/13301536/422e0b90-dafa-11e5-999d-439a75657c31.PNG)

This is happening in Chrome and Safari on an iPad Mini running iOS 8.0.

Incidentally, when you start a video playing on an iPad, and then during the course of the video you switch to fullscreen mode, when you first enter fullscreen mode, the first two or three captions you see will be positioned correctly, before it reverts to displaying too low and getting cut off.

**Comment by robwalch** [comment] 2016-02-24 22:50
@kylesessions can you share url with a player that duplicates this issue? Where are you loading 7.3.2 from? Do you have any CSS transforms on the player or video tag?

Thanks!

**Comment by esboyd** [comment] 2016-02-24 23:23
@kylesessions can you throw up a page using the intro video and JW 7.3.2? Thanks!

**Comment by kylesessions** [comment] 2016-02-24 23:44
@robwalch and @esboyd Thanks for the assistance. I'm using a self-hosted player. I downloaded 7.3.2 via the `License Keys & Downloads` link in the dashboard of my account. I do not have any CSS transforms on the player or video tag. I came across a suggestion on stackoverflow earlier about adding `webkit-transform: scale(1, 1)` to either the video element itself, or the container element, so I tried that, but it didn't seem to solve the problem.

Test page is here: https://s3.amazonaws.com/fgs-public/vidTest/vidTest3.html

The test page has 7.3.2, but I wasn't sure what you meant by the intro video, so I just used the video and captions from the front page of the site I'm working on.

**Comment by robwalch** [comment] 2016-02-25 20:55
If the problem only manifests in iOS 8 and not iOS 9, it's a third party issue. We've made sure to not scale video in iOS when possible. There are limitations to video positioning and issues with captions texttracks in iOS 8 that we cannot address. Users should update their devices or watch video in fullscreen if they wish to view captions.

**Comment by kylesessions** [comment] 2016-02-27 01:00
Thanks @robwalch. I checked out my test page on an iPad running iOS 9 and the issue is NOT present; caption placement is fine. Weird though; my test page doesn't have any 3rd-party libraries on it.

In any case, we discovered a fix/workaround for iOS 8 - you need to include positioning data in the `.vtt` files. When I added a line position to my `.vtt` files, the player on iPad respected that and placed the captions correctly. For example, without positioning:

```
00:00:00.100 --> 00:00:01.500
When it comes to pleasure,

00:00:01.500 --> 00:00:05.500
like actual techniques and what works for women,

00:00:05.500 --> 00:00:09.000
there’s never been any large-scale research done.
```

With positioning:
```
00:00:00.100 --> 00:00:01.500 line:90%
When it comes to pleasure,

00:00:01.500 --> 00:00:05.500 line:90%
like actual techniques and what works for women,

00:00:05.500 --> 00:00:09.000 line:90%
there’s never been any large-scale research done.
```

**Comment by fdambrosio** [comment] 2016-03-01 17:55
@robwalch Now I can show an example link: http://www.fdambrosio.net/test/player7/audio.html 
There's a problem with captions and audio hls stream: the captions shift under the control bar when the mouse cursor isn't over the player screen. I've tested with 7.3.4 and Safari/Chrome/Firefox on Mac

**Comment by robwalch** [comment] 2016-03-02 20:33
Thanks @fdambrosio,

When we changed the css to always show the controlbar with .jw-flag-media-audio, we did not also make  sure to force the vertical positioning of captions to display over it while .jw-flag-user-inactive is present.

**Comment by fdambrosio** [comment] 2016-03-03 16:38
Thanks @robwalch for this fix. How can I use a css workaround waiting vers. 7.4?

**Comment by robwalch** [comment] 2016-03-03 17:56
Hi @fdambrosio,

Give this a try. This is from the fix just merged into master. It appears to do just the trick on your test page:
```css
.jwplayer.jw-flag-media-audio.jw-flag-user-inactive.jw-state-playing .jw-captions {
   bottom: 3em;
}
```

**Closed** 2016-04-22 20:17 UTC
