### ISSUE TITLE
Choose playback plugin by name

### ISSUE THREAD

**Issue by shaharmor** [jwplayer/jwplayer#981] opened 2016-01-04 13:23 UTC
Hi,

Currently its not possible to choose a specific playback plugin by its name, for example if i add multiple plugins named `plugin1` & `plugin2`, i want to be able to choose which one will play my stream by adding `primary: 'plugin1'` to the config.

Any chance to make it happen?

**Comment by robwalch** [comment] 2016-01-04 20:28
Isn't this a duplicate of your other request #983?

**Closed by robwalch** 2016-01-04 20:28 UTC
