### ISSUE TITLE
Audio HLS/DASH could not be played on iOS

### ISSUE THREAD

**Issue by fdambrosio** [jwplayer/jwplayer#1155] opened 2016-04-28 14:48 UTC
We have a problem with audio files streamed by Wowza using Jwplayer 7.4
The stream works on desktop (Chrome / Firefox) but it doesn't works on iOS (9.x tested). 
When we try to play on IOS return error "file could not be played" but the file is an .m4a with aac codec that already works with jwplayer 6. 
The problem occurs when we use HLS or DASH (or both) protocol. 
 
test page: fdambrosio.net/test/player7/audio.html 

screenshot: 
![17d2c8bf-3166-4a52-a1d5-8c16dcb71b67](https://cloud.githubusercontent.com/assets/2962823/14889813/9fcbb3cc-0d60-11e6-877c-740d2dbb5233.jpg)

**Comment by fdambrosio** [comment] 2016-04-28 15:12
Until 7.2.3 that audio files works without problems.

**Comment by dannyfinks** [comment] 2016-04-28 15:14
Hi @fdambrosio we've seen this issue before and it seems to be an issue with audio streams in a video tag with side-loaded captions in Safari. Would you be able to setup a video tag with the same m3u8 and side-loaded vtt and see if it works there? In 7.3 we started using native tracks for iOS/Safari. Here is an example of this issue with a video tag - http://playertest.longtailvideo.com/video-tag-captions.html

**Comment by fdambrosio** [comment] 2016-04-28 15:39
In the same page fdambrosio.net/test/player7/audio.html I've added a test for native <audio> tracks with/without <track>. Audio hls stream with track doesn't play. 
If we try video (mp4+aac / hls) with track the player works on iOS too with captions, try: fdambrosio.net/test/player7/index.html 

We have to use all our audio/video media with captions and html5, how we can do that?

**Comment by robwalch** [comment] 2016-04-28 15:44
Can you add the VTT file to Wowza so that it includes it as a subtitle track in the HLS stream? Embedded captions and subtitle tracks are supported in HLS. (not sure they are in Shaka 1.6.5 for DASH though).

btw I have filed bug #25980997 with Apple regarding this issue in iOS and OS X Safari.

**Comment by fdambrosio** [comment] 2016-04-28 15:46
No, we can't add automatically vtt with wowza. It's possible to disable captions on iphone?

**Comment by fdambrosio** [comment] 2016-05-04 13:37
there's news about this problem?

**Comment by robwalch** [comment] 2016-05-04 16:00
@egreaves can you have a look at the test and see if this will be resolved in 7.4.1, or if it's CORS issue with the media as in https://bugs.chromium.org/p/chromium/issues/detail?id=608499&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort= ?

**Comment by fdambrosio** [comment] 2016-05-06 09:16
@robwalch @egreaves how can I test 7.4.1 ?

**Comment by fdambrosio** [comment] 2016-05-06 12:38
I've tested with https://ssl.p.jwpcdn.com/player/v/7.4.1-rc.1/jwplayer.js 
and bug is still here: audio hls/dash with vtt subtitles could not be played on iOS

**Comment by egreaves** [comment] 2016-05-06 21:53
Hi @fdambrosio,

I've done some testing and confirmed that loading VTT subtitles from a different domain than the video's source will result in a decode error in Safari, both on iOS and Desktop. As you've observed in Chrome, it's possible to load VTT files from a different domain if the video is served with CORS headers and the video element has the `crossorigin="anonymous"` attribute. 

We will be submitting a bug report to Safari detailing the issue. In the meantime, we'll be prioritizing a workaround to mitigate this and will tag this issue with the version that will include the fix.

**Comment by fdambrosio** [comment] 2016-05-09 12:12
thanks @egreaves ! 
I'm investigating how to set crossorigin 'anonymous' in Wowza, but it seems that I have to add it inside <video> tag of which I have no control 
https://www.wowza.com/forums/content.php?727-How-to-use-Google-Shaka-Player-with-Wowza-Streaming-Engine-(MPEG-DASH)

**Comment by fdambrosio** [comment] 2016-05-16 09:58
There's a workaround for v. 7.4.2 waiting 7.5.0 support?

**Comment by egreaves** [comment] 2016-05-16 15:02
@fdambrosio yes, there will be. The player will add tracks and cues to the video element by parsing VTT files instead of adding the VTT files to the DOM, thereby circumventing the CORS issue in Safari (iOS). This will be in the v7.5.0 release.

**Comment by fdambrosio** [comment] 2016-05-18 14:46
@egreaves thanks, but there's no workaround before to release 7.5.0 ?

**Comment by fdambrosio** [comment] 2016-07-08 10:15
Hi, 
what about the 7.5 update?

**Comment by robwalch** [comment] 2016-07-28 00:16
We released 7.5 yesterday.

**Closed** 2016-09-09 15:28 UTC
Labels: third-party
