### ISSUE TITLE
fix play controlls after pausing in native iOS player

### ISSUE THREAD

**Issue by harryurban** [jwplayer/jwplayer#947] opened 2015-12-09 10:56 UTC
After hitting pause and exit in native iOS player the jwplayer shows the pause buttons in the controls. 
So I have to click once for switching it to play and a second time to resume playback.

**Comment by robwalch** [comment] 2015-12-09 14:10
Hi @harryurban,

This should be fixed in v7.2. Pausing using native controls in iOS full screen or PIP updates the playback state in JWPlayer. What version are you using?

Is there a test page you can share?

**Comment by harryurban** [comment] 2015-12-09 14:23
We're using 7.1.4. 
We will upgrade soon and close the issue if this is fixed. 

Thank you for the quick reply. :+1:

**Comment by robwalch** [comment] 2015-12-10 23:16
Here's the fix you're looking for https://github.com/jwplayer/jwplayer/pull/835

**Closed by robwalch** 2015-12-10 23:16 UTC

**Comment by robwalch** [comment] 2015-12-10 23:18
@harryurban feel free to reopen if this doesn't work for you in 7.2.

**Comment by harryurban** [comment] 2015-12-11 13:44
the version bump fixed it. thank you for your help.

**Comment by prathamesh-sonpatki** [comment] 2016-02-09 11:41
@robwalch I am still experiencing similar issue after upgrading to jwplayer 7.2.4. Whenever I click "Done" in the native video player, jwplayer minimizes the native player but still shows "pause" button. I have to click it again and only then "play" button appears.

**Comment by prathamesh-sonpatki** [comment] 2016-02-09 11:50
I am noticing this for playlist as well as normal videos. Tested on iphone 6 plus. Please let me know if you need more details. Thanks!

**Comment by robwalch** [comment] 2016-02-11 19:33
I'm unable to reproduce the issue with player v7.2.4 or v7.3.0 on iOS 9.2 on iPhone. Please provide and indicate the hardware and iOS version this issue is reproducible on and we can then reopen.
