### ISSUE TITLE
VTT captions do not display in Firefox

### ISSUE THREAD

**Issue by mattcoz** [jwplayer/jwplayer#1474] opened 2016-10-07 22:30 UTC
This is a bug that I noticed a while ago in Firefox Nightly but was told that it wouldn't be addressed  it appeared in Firefox Beta.

There seems to be a regression from 7.4.4 to 7.5.0 when displaying VTT captions. The file is loaded successfully and everything appears to be working, but they just don't display. Here is a reproduction page that shows that they worked in 7.4.4 but don't work in 7.5.0 or even the latest 7.7.0.

https://www.arclearn.com:8443/jwplayertest-captions.jsp?version=7.4.4
https://www.arclearn.com:8443/jwplayertest-captions.jsp?version=7.5.0
https://www.arclearn.com:8443/jwplayertest-captions.jsp?version=7.7.0

**Comment by johnBartos** [comment] 2016-10-10 20:35
Hey @mattcoz, we'll look into this but yeah, Firefox Beta is a lower priority. They usually fix Captions issues before the release version.

**Comment by mattcoz** [comment] 2016-10-11 16:32
So you're saying the problem is with Firefox? Then why do previous versions of JW Player work? Is it trying to display them natively? I thought that was only supported in Chrome.

**Comment by mattcoz** [comment] 2016-10-17 17:41
I see 7.7.1 has some fixes for captions in Firefox, but I can confirm that it does not fix this issue. I've also added a second test to this page with a simple native video element with an MP4 source and a track element. This shows that Firefox has no problem rendering the captions, but I didn't think JW Player was even using native rendering in Firefox.

https://www.arclearn.com:8443/jwplayertest-captions.jsp?version=7.7.1

**Comment by mattcoz** [comment] 2016-11-09 17:08
Less than a week before Firefox 50 is released and no response? I ran mozregession on Firefox to see what of their changes could have played a part and I found this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1276831

It still doesn't make sense to me why this is a problem if you're not using the native VTT rendering, and the native rendering works perfectly with the same VTT file. So, please do whatever you need to do to find out why you are incompatible with this change. Or at least give me something I can provide to the Firefox developers that shows that it is their problem.

**Comment by mattcoz** [comment] 2016-11-15 16:21
Firefox 50 has now been released so I've updated the title to reflect that.

**Comment by johnBartos** [comment] 2016-11-15 16:47
@mattcoz Our new hls library uses native rendering for VTT captions on Firefox so it will work there for hls playback. I've confirmed your issue though - thanks a lot for the report. We'll get a fix in for this asap.

We don't use native rendering for VTT in firefox since they don't allow us to style the shadow dom.

**Comment by johnBartos** [comment] 2016-11-15 16:48
That diff helped a lot - Member of DoubleOrAutoKeyword 'undefined' is not a valid value for enumeration AutoKeyword in vttparser.js, line 196

**Comment by mattcoz** [comment] 2016-11-15 21:27
I think I found the problem, it's in the following code:

`cue.position = settings.get('position', {
                start: 0,
                left: 0,
                middle: 50,
                end: 100,
                right: 100
}, cue.align)`

The problem is that "middle" is not valid, the correct key is "center". The error is thrown when you try to set the position value to undefined.

I've created a pull request to replace "middle" with "center".

**Comment by johnBartos** [comment] 2016-11-16 17:11
Closed via https://github.com/jwplayer/jwplayer/pull/1553

**Closed by johnBartos** 2016-11-16 17:11 UTC
Labels: bug, needs-review
