### ISSUE TITLE
VAST Tracking event="progress" not triggering

### ISSUE THREAD

**Issue by kkontus** [jwplayer/jwplayer#2764] opened 2018-03-06 11:35 UTC
### Expected Behavior

*Trigger "progress" event set in VAST Tracking events*

### Actual Behavior

*It's not triggering 'progress' Tracking events, even though they are part of official VAST 3.0 and 4.0 specification.
It works for some other events, like firstQuartile, midpoint.
Is progress removed even though it's a part of VAST spec?*

### Steps to reproduce
Based on example here: https://support.jwplayer.com/customer/portal/articles/1482127

1. Include jwplayer 7.11.2
```
<script src="https://ssl.p.jwpcdn.com/player/v/7.11.2/jwplayer.js"></script>
<script>jwplayer.key="our-key";</script>
```

2. 
```
<div id="my-video"></div>

<script type="text/javascript">

var jw = jwplayer("my-video");
jw.setup({
    file: "https://content.jwplatform.com/videos/Wf8BfcSt-kNspJqnJ.mp4",
    image: "https://content.jwplatform.com/thumbs/Wf8BfcSt-640.jpg",
    width: "640",
    height: "480",
        advertising: {
            client: "vast",
            tag: "vastTag.xml"
        }
});

</script>
```

3.
VAST Tracking Event node

```
<TrackingEvents>
    <Tracking event="progress" offset="00:00:10.000"><![CDATA[https://test.test.com/view.php?tracking_event=progress&progress=00:00:10.000&idzone=1234567]]></Tracking>
</TrackingEvents>
```

As I said, it works fine with below, but it doesn't with progress
```
<TrackingEvents>
              <Tracking event="start">http://example.com/pixel.gif</Tracking>
              <Tracking event="firstQuartile">http://example.com/pixel.gif</Tracking>
              <Tracking event="midpoint">http://example.com/pixel.gif</Tracking>
              <Tracking event="thirdQuartile">http://example.com/pixel.gif</Tracking>
              <Tracking event="complete">http://example.com/pixel.gif</Tracking>
              <Tracking event="pause">http://example.com/pixel.gif</Tracking>
              <Tracking event="mute">http://example.com/pixel.gif</Tracking>
              <Tracking event="fullscreen">http://example.com/pixel.gif</Tracking>
</TrackingEvents>
```

### Environment

- *Multiple mobile and desktop*
- *MacOS, Ubuntu*
- *Firefox, Chrome*
- *JW Player 7.11.2 and up*

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnBartos** [comment] 2018-03-06 20:45
@kkontus Thanks for the report. Did you test this with the latest JW8 version?

**Comment by kkontus** [comment] 2018-03-07 11:07
Hi @johnBartos , I only tested it on JW6 and JW7

**Comment by zetagame** [comment] 2019-04-15 21:12
@kkontus Ads are no longer part of our open source player, but the issue is fixed in the latest issue of our commercial player. 

For more info check out: [https://developer.jwplayer.com/sign-up/]
Or if you're interested in premium plans: [https://www.jwplayer.com/pricing/]

**Closed** 2019-04-22 21:08 UTC
Labels: answered
