### ISSUE TITLE
Videos in supported format cannot be played on iOS devices

### ISSUE THREAD

**Issue by gsuhajda** [jwplayer/jwplayer#3053] opened 2018-09-06 15:51 UTC
### Expected Behavior

MP4/H.264/AAC videos can be played on desktop and mobile devices as well.

### Actual Behavior

Many of our videos cannot be played on iOS devices, while others work fine. All videos can be played on desktop devices.

Error message: "This video cannot be played. Error code: 224003"
...meaning that the video format is not correct, however we encoded all videos according to the JW Player format reference (https://support.jwplayer.com/articles/supported-video-and-audio-formats-reference).
Double-checked every parameter of the player and the encodings, still unable to resolve the issue.

### Steps to reproduce

Open a video on iPhone/iPad, e.g.: 
http://www.cultureclub.hu/modigliani-kiallitas-a-magyar-nemzeti-galeriaban/
http://www.cultureclub.hu/fortepan/

This one is working fine: http://www.cultureclub.hu/lajko-felix-szimfonik/

### Environment

- iPhone/iPad
- latest iOS
- Safari and Chrome
- JW Player version 8.5.3

Thanks for your help.

**Comment by dannyfinks** [comment] 2018-09-06 15:58
@gsuhajda there may be something wrong with the encoding. If you directly enter the mp4 URL into the iOS Safari browser it will not play in the browser natively as well. I tried with http://www.cultureclub.hu/video/kiallitas/Modigliani.mp4

**Comment by gsuhajda** [comment] 2018-09-06 16:07
@dannyfinks thanks for noticing, we're looking to it!

**Comment by dannyfinks** [comment] 2018-09-07 15:55
Sounds good @gsuhajda I am going to close this out. Feel free to reopen if your investigation finds anything that may be specific to jwplayer.

**Closed by dannyfinks** 2018-09-07 15:55 UTC

**Comment by partyspy** [comment] 2019-02-26 07:21
The same issue still appear now. Have you guys found any solutions?

**Comment by karimMourra** [comment] 2019-02-26 19:02
@partyspy do you have sample streams ?

**Comment by partyspy** [comment] 2019-02-26 19:07
@karimMourra I've found out where the problem is. It's a google hosted video stream and it's due to the firewall issue. Thx.

**Comment by trinhtaicon** [comment] 2019-12-07 07:54
> @karimMourra I've found out where the problem is. It's a google hosted video stream and it's due to a firewall issue. Thx.

how did you fix it bro, please share it
