### ISSUE TITLE
Vast with flash video as first media file cannot be played with primary:"html5"

### ISSUE THREAD

**Issue by braznaavtrav** [jwplayer/jwplayer#1543] opened 2016-11-11 17:47 UTC
When using the `primary: 'html5'` configuration, loading a vast ad tag with `MediaFiles` set up as so:
```
<MediaFiles>
    <MediaFile delivery="progressive" width="16" height="9" type="video/x-flv" bitrate="600" apiFramework="NONE">
        <![CDATA[ https://someurl.flv ]]>
    </MediaFile>
    <MediaFile delivery="progressive" width="16" height="9" type="video/mp4" bitrate="600" apiFramework="NONE">
        <![CDATA[ https://someurl.mp4 ]]>
    </MediaFile>
    <MediaFile delivery="progressive" width="16" height="9" type="video/webm" bitrate="600" apiFramework="NONE">
        <![CDATA[ https://someurl.webm ]]>
    </MediaFile>
</MediaFiles>
```
the ad video will not load. If the flv file is moved last in the `MediaFiles` list the ad video will load without issue.

### Expected Behavior

My understanding of this may be wrong, so please correct me if it is, but I would expect the player to fallback to the second video file if the first video file fails to load for any reason.

### Actual Behavior

The player either permanently stalls with the loading spinner, or skips straight to the main video file without displaying the ad.

### Steps to reproduce

The easiest way to reproduce this is in the [JW Player Ad Tester](http://demo.jwplayer.com/ad-tester/). Using HTML5 as the rendering mode (`primary: 'html5'`), and "Pre-Roll" as the Ad Position, try loading the following files in "Ad Tag to Load":

- https://media.bidr.io/qa/1/1/vast-flash-test-1.xml which has a flash video file as first element in `MediaFiles` list and will either permanently stall or immediately play the main video file without displaying the ad video
- https://media.bidr.io/qa/1/1/vast-flash-test-2.xml which has an `mp4` file as the first element and `flv` as the last element in `MediaFiles` will correctly play the ad video before playing the main video.

### Environment

- Hardware: 
    - MacBook Pro (Retina, 13-inch, Early 2015)
    - Processor: 2.7 GHz Intel Core i5
    - Memory: 16 GB 1867 MHz DDR3
    - Graphics: Intel Iris Graphics 6100 1536 MB
- OS: OSX El Capitan 10.11.3
- Browser: Chrome  53.0.2785.143 (64-bit)
- JW Version: 
    - http://demo.jwplayer.com/ad-tester/
    - jwplayer.version: `"7.7.4+commercial_v7-7-4.127.commercial.8c45ad.jwplayer.39d271.freewheel.32fc26.googima.17c8c6.vast.10bf30.analytics.516c4b.plugin-gapro.7e936b.plugin-related.b37675.plugin-sharing.8b8aae"`

**Comment by johnBartos** [comment] 2016-11-15 20:08
We're looking into this but afaik our test suites for this case pass.

**Comment by braznaavtrav** [comment] 2016-11-16 19:35
@johnBartos can point me to a test case that tests this scenario or a similar one?

**Comment by sterpe** [comment] 2016-12-21 20:28
@braznaavtrav I believe your issue is caused by your media server, which does not supply the correct CORS headers for the `html5` version of jwplayer to access the requisite xml document.

```
XMLHttpRequest cannot load https://media.bidr.io/qa/1/1/vast-flash-test-1.xml. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://demo.jwplayer.com' is therefore not allowed access.
```

@johnBartos I believe you can close this.

**Comment by sterpe** [comment] 2016-12-21 20:30
@braznaavtrav GET https://media.bidr.io/qa/1/1/vast-flash-test-1.xml
```
Accept-Ranges →bytes
Age →783
Connection →keep-alive
Content-Length →2867
Content-Type →application/xml
Date →Wed, 21 Dec 2016 20:17:04 GMT
ETag →"55059172e9603ab349271a537d469945"
Last-Modified →Wed, 09 Nov 2016 20:32:28 GMT
Server →AmazonS3
Via →1.1 b08d3fd1ea7c0f4b62f5adbb976ab099.cloudfront.net (CloudFront)
X-Amz-Cf-Id →vUuWqfvKrvPSuNsYw71ZPQE_o5l5WLy_fURALZwqSMTBMjP803cQEw==
X-Cache →Hit from cloudfront
```

**Comment by johnBartos** [comment] 2016-12-21 20:42
@sterpe Thanks for the help! I'll give @braznaavtrav a chance to reply before closing

**Comment by sterpe** [comment] 2016-12-21 20:56
np.  I'm fairly sure this is not an issue with `jwplayer` since our VAST server always put the `.flv` file first, since VAST 1.0 players generally don't assume multiple fallback mime-types, and we haven't had a problem.

**Comment by braznaavtrav** [comment] 2017-01-05 16:44
Sorry for the delayed response. Interestingly enough, this bug seems to be fixed in the jwplayer ad tester even with the presence of the CORS error. Closing the issue.

**Comment by robwalch** [comment] 2017-03-15 16:24
Ads should put "video/mp4" first and remove flv sources all together.

**Closed by robwalch** 2017-03-15 16:24 UTC
