### ISSUE TITLE
Captions not showing by default on iPhone

### ISSUE THREAD

**Issue by kylesessions** [jwplayer/jwplayer#1128] opened 2016-04-12 17:47 UTC
### Expected Behavior
When instantiating a player object with `jwplayer.playlist[n].tracks[n].default` set to `true`, the captions from `tracks[n]` should be displayed when the video is played.

### Actual Behavior

On iPhones, when the video is played, no captions are displayed until the user uses the iPhone's full-screen video UI to activate the desired captions track.

### Steps to reproduce

1. On an iPhone running iOS 9.x, visit www.omgyes.com/de/ (note: it is important to visit the German version, as captions are supposed to be turned off by default in English, but on in other site languages)
2. Tap the play icon in the top section of the page, beneath the text `... auf der Grundlage aktueller Forschung.` Sometimes the video won't load and the player will display the `!` triangle icon. In this case, simply reload the page and try again.
3. When the video is playing, observe no subtitles/captions. Then use the phone's UI to activate the `Deutsch` caption track and observe the captions appear.

### Environment

- iPhone 5/6
- iOS 9.x
- JW Player version 7.3.2, URL: www.omgyes.com/de/

**Comment by robwalch** [comment] 2016-04-22 20:59
@egreaves please investigate.

**Comment by egreaves** [comment] 2016-04-25 14:46
@kylesessions Thanks for pointing this out. This is caused by the captions tracks not being loaded before the player attempts to set the default index. We will be addressing this as part of the captions improvements slated for 7.5.

**Comment by robwalch** [comment] 2016-04-26 17:53
Let's get this in our next patch.

**Comment by fdambrosio** [comment] 2016-07-11 09:52
Hi,
I'm testing 7.5.0 beta 1 with audio captions. 
Now it works and the issue seems to be solved, but on iPhone player starts in fullscreen mode and caption text is cutted and aligned on the left.

test: http://www.fdambrosio.net/test/player7/audio-750.html

iPhone 5S
iOS 9
jwplayer 7.5.0 beta 1

**Comment by egreaves** [comment] 2016-07-26 20:30
Closing this issue since it was addressed in 7.4.1. We'll track @fdambrosio's comment in this more recent issue: to https://github.com/jwplayer/jwplayer/issues/1324

**Closed by egreaves** 2016-07-26 20:30 UTC
Labels: bug
