### ISSUE TITLE
Missing quality selector

### ISSUE THREAD

**Issue by kasty** [jwplayer/jwplayer#1456] opened 2016-09-29 15:56 UTC
The « levels » event is not triggered after playing a preroll on a HLS video with jwplayer in flash mode. This induces the quality selector is never displayed.

### Steps to reproduce

1. Don't use any adblocker
2. Visit this url and see that there's no "settings" button : http://player-v3-dev.arte.tv/index.php?json_url=https%3A%2F%2Fapi.arte.tv%2Fapi%2Fplayer%2Fv1%2Fconfig%2Ffr%2F052808-001-A%3Fautostart%3D0%26lifeCycle%3D1&lang=fr_FR&config=arte_tvguide
3. Active your adblocker and refresh the page : the settings button appears

I made some tests and I can tell that the "levels" event is never triggered in this problematic case described above

### Environment

- *MacBook Air*
- *OS X El Capitan / Chrome Version 53.0.2785.116 / Firefox 49.0.1 / Flash Version 23*
- *JW Player 7.6.0*

**Comment by johnBartos** [comment] 2016-09-29 15:59
It's saying "This video is not available in your country". Can you give us an example that works over here in the States?

**Comment by kasty** [comment] 2016-09-30 07:56
Yes sorry, it's a bit complicated to find an example that both works worldwide and have an advertising. This one should work : http://player-v3-dev.arte.tv/index.php?json_url=https%3A%2F%2Fapi.arte.tv%2Fapi%2Fplayer%2Fv1%2Fconfig%2Ffr%2F060770-000-A%3Fautostart%3D0%26lifeCycle%3D1&lang=fr_FR&config=arte_tvguide&autostart=1

I can also precise that the preroll is played with your playAd() method called inside the beforePlay event.

**Comment by johnBartos** [comment] 2016-09-30 21:31
How are you putting this icon into the controlbar? I see that your icon has been loaded but your div isn't in the DOM. Maybe the JS which puts your menu in our controlbar is broken?

![screen shot 2016-09-30 at 17 31 01](https://cloud.githubusercontent.com/assets/5042276/19007594/c55d53d2-8733-11e6-9877-72e009e39712.png)
![screen shot 2016-09-30 at 17 29 30](https://cloud.githubusercontent.com/assets/5042276/19007595/c560302a-8733-11e6-8488-f36263295bec.png)

**Comment by kasty** [comment] 2016-10-13 10:32
No, that's not a DOM problem. We clearly identify that the levels events is not trigger after that a preroll is played

**Comment by robwalch** [comment] 2016-10-18 18:40
Hi @kasty, It looks like the "level" event fires, but it does not contain any levels. I'm looking into why... this is a file called settings.js on your website. It is not part of our player:

```js
/**
 * This is a special case to force settings button display if there are some versions and if the settings button has not already been display in the levels event
 * @see PLAYER-1012 + PLAYER-1011
 */
self.jwplayer.on('play', function() {

    if(!self.settingsBtnTested &&
        $(this.getContainer()).find(self.$el).length == 0) {
        self.jwplayer.trigger('levels'); 
    }
    
    // don't try anymore
    self.settingsBtnTested = true;
});
```

Triggering levels without an event object causes a JavaScript exception later in code this is part of your site and not part of jwplayer.

This might work if you made the event include an event object that included the expected data:

```js
self.jwplayer.trigger('levels', {
    levels: self.jwplayer.getQualityLevels()
    currentQuality:  self.jwplayer.getCurrentQuality()
}); 
```

**Comment by robwalch** [comment] 2016-10-18 18:46
I confirmed this is not an issue in 7.7.2. It appears to be an issue with your implementation caused by error resulting from the code I pointed out above.

If updating to 7.7.2 and resolving the issue above does not fix it feel free to reopen the ticket with an updated example.

**Closed by robwalch** 2016-10-18 18:46 UTC

**Comment by robwalch** [comment] 2016-10-18 19:01
@kasty I noticed a couple of other things in your implementation:

In order for prerolls to work correctly with `playAd`, `playAd` should be called synchronously inside the 'beforePlay' handler. It should not be inside a timeout with `setTimeout`.

```js
//play ad if there is one (ad play only when play icon is clicked
self.jwplayer.on('beforePlay', function(evt){
    var vastUrl = self.options.vast_url;
    if(!arte_vp.adPlayed && !_.isNull(vastUrl)){
        setTimeout(function(){
            self.jwplayer.playAd(vastUrl);
        },0);
    }
});
return self.jwplayer;
```

Any reason setting tag in the `advertising` block of the config or playlist item does not work for you?
